server:
  port: 8080

spring:
  messages:
    basename: messages/messages

  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DBNAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  packages-to-scan: com.noah.sns.poke
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

jwt:
  secret: 4939445d52275a489b61c47726dd63e7cdf80a876927e9ddc1cd682edccbe686de9a2aab15ad84dd06e6727612ee684140ce9cf29960875212480d171d270858